import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("live trading exports research-only quote, depth, and local controls", async () => {
  const source = await readFile(new URL("workspace.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("workspace.module.css", import.meta.url), "utf8");

  for (const label of ["Portfolio holdings", "Pause visual strip", "Pop out", "Market depth", "Research notes", "Price alerts", "Forecast this instrument", "Add to watchlist"]) assert.match(source, new RegExp(label));
  assert.equal((source.match(/data-research-action=/g) ?? []).length, 2);
  for (const call of source.matchAll(/fetch\((?:`|")([^`"]+)/g)) assert.match(call[1], /^\/api\/v1\//);
  assert.match(source, /\/api\/v1\/lists\?kind=portfolio/);
  assert.match(source, /\/api\/v1\/instruments\?/);
  assert.match(source, /JSON\.stringify\(\{ kind: "portfolio"/);
  assert.match(source, /item: \{ symbol: entry\.symbol, asset_type: assetType, quantity: entry\.quantity \}/);
  assert.match(source, /\/api\/v1\/lists\?kind=portfolio&symbol=/);
  assert.match(source, /\/api\/v1\/quotes\?symbols=/);
  assert.match(source, /quoteBatches\(symbols\)/);
  assert.match(source, /record\(payload\)\.items/);
  assert.match(source, /local (list|quote) response was malformed/);
  assert.doesNotMatch(source, /Array\.isArray\(payload\)|payloadRecord\.quotes|payloadRecord\.symbol/);
  assert.doesNotMatch(source, /\/api\/v1\/market-depth|Depth request failed/);
  const watchlistRequest = source.match(/async function addToWatchlist\(\)[^]*?setWatchlistMessage\("Added to watchlist\."\);/)?.[0] ?? "";
  assert.ok(watchlistRequest);
  assert.match(watchlistRequest, /await apiPayload\(response, `Watchlist update failed \(\$\{response\.status\}\)\.`\);/);
  assert.doesNotMatch(watchlistRequest, /501|Watchlists are not implemented/);
  assert.doesNotMatch(source, />\s*(Buy|Sell)\s*</i);
  for (const disclosure of ["Provider:", "As of:", "Delay:", "Free data has no Nasdaq TotalView or exchange-depth entitlement", "No rows are fabricated"]) assert.match(source, new RegExp(disclosure));
  assert.doesNotMatch(source, /\["Time", "M", "MID"/);
  assert.doesNotMatch(source, /stock-probs\.portfolio-draft|using local draft|Local portfolio draft/);
  assert.match(source, /stock-probs\.live-notes/);
  assert.doesNotMatch(source, /type Identity = \{[^}]*name|name: (?:items\[0\]|quote)\.name|entitlement\?:/);
  assert.match(source, /selectedQuote\?\.name/);
  for (const field of ["change_percent", "volume", "open", "high", "low", "previous_close", "last_trade"]) assert.match(source, new RegExp(`selectedQuote\\?\\.${field}`));
  assert.doesNotMatch(source, /\["Close", selectedQuote\?\.last/);
  assert.match(source, /Previous close/);
  assert.match(source, /import \{[^}]*quotePrice[^}]*\} from "\.\.\/client-utils"/);
  assert.doesNotMatch(source, /function quotePrice/);
  assert.match(source, /window\.open\(`\$\{window\.location\.pathname\}\?\$\{identityQuery\(identity\)\}`/);
  assert.match(source, /provider: identity\.provider/);
  assert.match(source, /display_name: identity\.displayName/);
  assert.doesNotMatch(source, /popout=1/);
  assert.match(source, /SYMBOL: quantity/);
  assert.match(source, /quantity: entry\.quantity/);
  assert.match(source, /SHOP\.TO/);
  assert.match(source, /setInterval\(.*QUOTE_REFRESH_MS/);
  assert.match(source, /clearInterval\(timer\)/);
  assert.match(source, /request\?\.abort\(\)/);
  assert.match(source, /aria-hidden=\{duplicate/);
  assert.match(css, /transform:translateX\(-50%\)/);
  assert.match(source, /Snapshots refresh every 30 seconds/);
  assert.match(source, /snapshotState/);
  for (const line of source.split("\n").filter((line) => line.includes("JSON.stringify({ kind:"))) assert.doesNotMatch(line, /\b(name|exchange)\b/);
});
